#addons:
# apt_packages:
  #- rpm
  #- fakeroot

language:
    - java

jdk:
    - openjdk7

env:
   -  ciserver=true

before_install:
   - rm -f ~/bookdb.*
   - sudo apt-get rpm
   - sudo apt-get fakeroot
   - mvn clean

script:
   - mvn install

