sudo: required

language:
    - java

services:
  - docker

jdk:
    - openjdk7
#    - oraclejdk7

env:
   -  ciserver=true

before_install:
   - rm -f ~/bookdb.*
   - mvn -Pciserver clean 

script:
   - mvn install -Pciserver -fae

